### ISSUE TITLE
non-PTB dataset might crash the session

### ISSUE THREAD

**Issue by tastyminerals** [uds-lsv/TF-NNLM-TK#1]
The model won't work if you try to test it on some non-PTB dataset because `words = np.array(list(map(self.vocab.get, words)))` line will create `None` in numpy array in case of OOV tokens which in turn will crash at `vals = session.run(fetches, feed_dict)` during model testing.

Quick fix could be something like this: `np.array(list(map(lambda x: self.vocab.get(x) or self.vocab['<unk>'], words)))`

**Comment by michael-aloys** [comment]
Hi,

thanks for your feedback! 

In general, the DataProcessor should take care of replacing unknown words with the '<unk>' OOV token if it's parameter is_training is set to False (i.e. if it is in test-mode):

https://github.com/uds-lsv/TF-NNLM-TK/blob/master-public/data_processor.py#L101

However, there is a problem in the test.py (which calls the DataProcessor and which I assume is the one you used for testing). Currently, the vocabulary.pkl file is not stored with the model. Also, in test-mode, DataProcessor expects the vocabulary file to be in the same directory as the data, so it would anyways ignore the model's vocabulary. I'll look into that.

**A simple fix for the current version**:
(Assuming you use test.py for testing the model) Put your test file in the same directory as your training data. The DataProcessor will then find the vocabulary that was created on the training data and use it. DataProcessor will take care of the replacement of unknown words.

**Comment by tastyminerals** [comment]
Yes, you are correct. 
It appears that I was reusing `data_processor.py` code to adapt to a custom dataset and intentionally skipped the `self.unk` field with the corresponding code because "unk" was already included in my dataset vocabs. Hence the error. 
Thank you. Closing.

**Comment by michael-aloys** [comment]
The commit https://github.com/uds-lsv/TF-NNLM-TK/commit/71b416f3d8f51c24d1b1838e8259d70b4c5438b0 should fix this issue with the vocabulary file. The vocabulary file is now stored in the model directory and loaded from there when testing. Therefore, it is now independent of the test files and their location.
